// Repo intelligence: conventions + import-graph context for agent prompts.
//
// On session create we analyze the BASE repo:
//   1. `conventions discover --format json` (steph-dove/klaussy-repo-conventions) →
//      .conventions/conventions.raw.json with the import graph (fan-in/out,
//      cycles, clusters, endpoint chains). Pure static analysis.
//   2. `klaussy init --repo <base> -b <default>` (steph-dove/klaussy-agents) →
//      CLAUDE.md, .claude/rules/, conventions-aware skills
//      (.claude/skills/<repo>-review etc.), settings. Includes the Claude
//      CLI enrichment pass (no --skip-enrich) per product decision — the
//      richer CLAUDE.md is worth the API call. klaussy skips existing
//      files by default (no --force), so handcrafted CLAUDE.md survives.
//      Fallback when klaussy isn't installed: `conventions discover
//      --format claude` guarded by an atomic O_EXCL claim of CLAUDE.md
//      (that CLI overwrites unconditionally).
//
// From the artifacts we build one condensed "repository intelligence" prompt
// block, cached in memory + userData, injected into every agent prompt the
// app composes (PR review, plan, debug, implement). The artifacts themselves
// are also synced into each session worktree (CLAUDE.md, rules, skills) so
// interactive agents pick them up natively — worktrees only contain
// committed files, so without the sync Claude reports "no CLAUDE.md".
//
// Regeneration triggers: artifacts older than a week, artifacts changed on
// disk (mtime), or a new klaussy CLI version (stamped into both cache
// layers). Generation is fire-and-forget, per-repo single-flight, and
// broadcast to all windows (started / generated / fresh / failed) so the
// user always sees that analysis is happening. Failures degrade to prompts
// without the block.

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { execFileSync } = require('child_process');
const { app } = require('electron');
const { execFileP } = require('../util/exec');
const { baseRepoForWorktree } = require('../util/git-repo');
const { loadConfig, saveConfig } = require('../util/config');

const inflight = new Map();  // base repo path -> Promise
const memCache = new Map();  // base repo path -> { block, srcMtime, cliVersion }
const baseCache = new Map(); // worktree/repo path -> base repo path (immutable)
const freshNotified = new Set(); // repos already announced as cached this run
const failedAt = new Map();  // base repo path -> last failure timestamp
const FAIL_BACKOFF_MS = 10 * 60 * 1000; // don't re-attempt (or re-toast) failures more often than this

const STALE_MS = 7 * 24 * 60 * 60 * 1000; // weekly refresh
const CLAUDE_MD_CAP = 6000;  // chars of CLAUDE.md included in the block
const RULES_CAP = 4000;      // total chars of rule files included
const CLAUDE_MD_PLACEHOLDER = '# CLAUDE.md\n\n(being generated by klaussy-repo-conventions — if you can read this, a generation run was interrupted; delete this file)\n';

function artifactPaths(repoPath) {
  return {
    claudeMd: path.join(repoPath, 'CLAUDE.md'),
    rawJson: path.join(repoPath, '.conventions', 'conventions.raw.json'),
    rulesDir: path.join(repoPath, '.claude', 'rules'),
    skillsDir: path.join(repoPath, '.claude', 'skills'),
  };
}

// Hash-named cache file: path-derived names collide (/a/b-c vs /a/b/c) and
// contain Windows-invalid characters.
function cacheFileFor(repoPath) {
  const hash = crypto.createHash('sha1').update(repoPath).digest('hex');
  return path.join(app.getPath('userData'), 'repo-intel', hash + '.md');
}

function mtimeOf(p) {
  try { return fs.statSync(p).mtimeMs; } catch { return 0; }
}

// Newest mtime across all artifacts — the cache-coherency token. Includes the
// rules dir (its mtime bumps when rule files are added/removed).
function artifactsMtime(repoPath) {
  const a = artifactPaths(repoPath);
  return Math.max(mtimeOf(a.claudeMd), mtimeOf(a.rawJson), mtimeOf(a.rulesDir));
}

// Claude Code's recognized hook events. The pre-rename klausify scaffold wrote
// a `.claude/settings.json` with a `hooks.PreCommit` block (shape
// {command, description}) that isn't a real Claude Code hook event — so every
// time an agent loads such a repo, the claude CLI flags the unexpected
// property. We can't fix it by re-running `klaussy init` (it skips existing
// files without --force, which would also clobber a handcrafted CLAUDE.md and
// custom permissions), so we surgically strip the stray events instead.
const VALID_HOOK_EVENTS = new Set([
  'PreToolUse', 'PostToolUse', 'UserPromptSubmit', 'Notification',
  'Stop', 'SubagentStop', 'PreCompact', 'SessionStart', 'SessionEnd',
]);

// Remove unrecognized hook events from a repo's .claude/settings.json, in
// place. Best-effort and idempotent: no settings file, valid JSON we can't
// parse, or no stray events → no write. Returns the list of events removed.
function repairClaudeSettings(repoPath) {
  const file = path.join(repoPath, '.claude', 'settings.json');
  let raw;
  try {
    raw = fs.readFileSync(file, 'utf-8');
  } catch {
    return []; // no settings.json — nothing to repair
  }
  let cfg;
  try {
    cfg = JSON.parse(raw);
  } catch {
    return []; // malformed JSON — don't risk rewriting it
  }
  if (!cfg || typeof cfg !== 'object' || !cfg.hooks || typeof cfg.hooks !== 'object') return [];
  const stray = Object.keys(cfg.hooks).filter((k) => !VALID_HOOK_EVENTS.has(k));
  if (!stray.length) return [];
  for (const k of stray) delete cfg.hooks[k];
  if (!Object.keys(cfg.hooks).length) delete cfg.hooks; // don't leave an empty hooks:{}
  try {
    const nl = raw.endsWith('\n') ? '\n' : ''; // preserve trailing newline
    fs.writeFileSync(file, JSON.stringify(cfg, null, 2) + nl);
    console.log('[repo-intel] repaired .claude/settings.json in', repoPath,
      '— removed invalid hook event(s):', stray.join(', '));
  } catch (e) {
    console.warn('[repo-intel] settings repair failed for', repoPath + ':', e.message);
  }
  return stray;
}

// The command strings a hook entry runs (each klaussy hook runs a unique script).
function hookCommands(entry) {
  const out = new Set();
  for (const h of (entry && entry.hooks) || []) {
    if (h && typeof h.command === 'string') out.add(h.command);
  }
  return out;
}

// Merge klaussy-managed hook entries from a base .claude/settings.json into a
// worktree's already-existing one, keyed on each hook's command string. Adds
// only entries the worktree is missing — never removes or rewrites its own
// hooks, permissions, or other settings — so a worktree created BEFORE the base
// gained a hook (e.g. the pre-plan guidance hook) starts registering it without
// clobbering local edits. Best-effort: any parse/IO error leaves dst untouched.
function mergeMissingHooksIntoWorktree(srcPath, dstPath) {
  let src, dst, dstRaw;
  try {
    src = JSON.parse(fs.readFileSync(srcPath, 'utf-8'));
    dstRaw = fs.readFileSync(dstPath, 'utf-8');
    dst = JSON.parse(dstRaw);
  } catch {
    return; // missing/malformed on either side — don't risk a rewrite
  }
  const srcHooks = src && typeof src.hooks === 'object' ? src.hooks : null;
  if (!srcHooks || !dst || typeof dst !== 'object') return;
  const dstHooks = (dst.hooks && typeof dst.hooks === 'object') ? dst.hooks : (dst.hooks = {});
  let added = 0;
  for (const [event, entries] of Object.entries(srcHooks)) {
    if (!Array.isArray(entries)) continue;
    const dstList = Array.isArray(dstHooks[event]) ? dstHooks[event] : (dstHooks[event] = []);
    const present = new Set();
    for (const e of dstList) for (const c of hookCommands(e)) present.add(c);
    for (const e of entries) {
      const cmds = [...hookCommands(e)];
      if (cmds.length && cmds.every((c) => !present.has(c))) {
        dstList.push(e);
        for (const c of cmds) present.add(c);
        added++;
      }
    }
  }
  if (!added) return;
  try {
    const nl = dstRaw.endsWith('\n') ? '\n' : '';
    fs.writeFileSync(dstPath, JSON.stringify(dst, null, 2) + nl);
    console.log('[repo-intel] merged', added, 'missing hook(s) into', dstPath);
  } catch (e) {
    console.warn('[repo-intel] hook merge failed for', dstPath + ':', e.message);
  }
}

// klaussy CLI — command `klaussy` (PyPI `klaussy-agents`). We memoize BOTH
// which binary is on PATH and its version: the version doubles as the
// regeneration stamp ("redo when there is a new version"), and the resolved
// binary keeps the version probe and the `init` spawn in sync. A null result
// (not installed / transient spawn failure / probe raced the PATH fix) is
// cached only briefly so an install mid-run is picked up.
//
// The pre-rename `klausify` command is deliberately NOT probed as a fallback:
// an existing machine that still has klausify 0.2.x must upgrade to
// klaussy-agents (its new prompt templates are the whole point of the
// rename), so we ignore klausify here and let ensureReviewTools install the
// new package instead of silently running the stale CLI.
const KLAUSSY_VERSION_NULL_TTL_MS = 60 * 1000;
const AGENT_BINS = ['klaussy']; // klaussy-agents — no legacy klausify fallback
let klaussyCli = { bin: null, version: null, at: 0, promise: null };
function getKlaussyCli() {
  if (klaussyCli.promise) return klaussyCli.promise;
  if (klaussyCli.version) return Promise.resolve(klaussyCli);
  if (Date.now() - klaussyCli.at < KLAUSSY_VERSION_NULL_TTL_MS) return Promise.resolve(klaussyCli);
  const p = (async () => {
    for (const bin of AGENT_BINS) {
      try {
        const r = await execFileP(bin, ['--version'], { timeout: 15000 });
        const v = String(r.stdout).trim() || null;
        if (v) { klaussyCli = { bin, version: v, at: Date.now(), promise: null }; return klaussyCli; }
      } catch { /* not on PATH — fall through to the null result */ }
    }
    klaussyCli = { bin: null, version: null, at: Date.now(), promise: null };
    return klaussyCli;
  })();
  klaussyCli.promise = p;
  return p;
}

// Tell every window what's happening so the renderer can toast it — silent
// success reads as "nothing ran" and silent failure hides a missing CLI.
// Lazy require avoids a load-order dependency on state/windows.
function notifyWindows(payload) {
  try {
    const { allWindows } = require('./windows');
    for (const w of allWindows) {
      if (w && !w.isDestroyed()) w.webContents.send('repo-intel-event', payload);
    }
  } catch { /* no windows yet (early boot) — nothing to tell */ }
}

// First-run install of the analysis CLIs (klaussy-repo-conventions +
// klaussy-agents, both on PyPI). Without these, repo intelligence silently
// never works. Prefer pipx (isolated, installs to ~/.local/bin which is
// already on the spawn PATH); fall back to `python3 -m pip install --user`.
// Single-flight, one attempt per app run — never throws. Resolves true when
// both tools are available afterward.
let toolsPromise = null;
// Command name (what we run / detect) vs PyPI package name (what we install)
// — they differ for klaussy-agents (command `klaussy`). Presence is checked
// with `--help`: the `conventions` CLI has no `--version` flag, but all
// support `--help` and exit 0.
//
// Detection keys on the NEW command only. A machine that still has the
// pre-rename `klausify` command is treated as MISSING so it upgrades to
// klaussy-agents (and its new prompt templates) instead of being stuck on
// the legacy CLI. The `conventions` command is shared by the old
// `conventions-cli` and the new `klaussy-repo-conventions` (same command,
// same 1.4.x), so an existing `conventions` already satisfies it; we only
// install the new dist on machines that lack the command, since reinstalling
// over it would just collide on the pipx symlink for no behavior change.
const TOOLS = [
  { cmd: 'conventions', pkg: 'klaussy-repo-conventions' },
  { cmd: 'klaussy', pkg: 'klaussy-agents' },
];

async function toolPresent(cmd) {
  try {
    await execFileP(cmd, ['--help'], { timeout: 15000 });
    return true;
  } catch {
    return false;
  }
}

async function pickInstaller() {
  // Prefer isolated installers (pipx, uv): each tool gets its own venv, so they
  // are immune to PEP 668 "externally-managed-environment" rejections that a
  // Homebrew/Debian system Python raises against `pip install`.
  try {
    await execFileP('pipx', ['--version'], { timeout: 10000 });
    return { kind: 'pipx' };
  } catch { /* no pipx */ }
  try {
    await execFileP('uv', ['--version'], { timeout: 10000 });
    return { kind: 'uv' };
  } catch { /* no uv */ }
  for (const py of ['python3', 'python']) {
    try {
      await execFileP(py, ['-m', 'pip', '--version'], { timeout: 10000 });
      return { kind: 'pip', py };
    } catch { /* try next */ }
  }
  return null;
}

// Bootstrap pipx itself when the machine has Python but no isolated installer.
// Done silently in the background (no manual hand-off): Homebrew first (cleanest
// on macOS / Linuxbrew, no PEP 668), otherwise `pip install --user pipx` with
// the externally-managed escape hatch. Wires PATH via `pipx ensurepath` +
// refreshSpawnPath so the freshly-installed pipx is usable this session.
// Returns true only if `pipx` is callable afterwards.
async function bootstrapPipx(py) {
  const BIG = { timeout: 5 * 60 * 1000, maxBuffer: 16 * 1024 * 1024 };
  console.log('[repo-intel] no pipx/uv found — bootstrapping pipx in the background');
  let installed = false;
  try {
    await execFileP('brew', ['--version'], { timeout: 10000 });
    await execFileP('brew', ['install', 'pipx'], BIG);
    installed = true;
  } catch { /* no brew, or brew install failed — try pip below */ }
  if (!installed && py) {
    try {
      await execFileP(py, ['-m', 'pip', 'install', '--user', 'pipx'], BIG);
      installed = true;
    } catch (err) {
      const msg = (err && err.stderr ? String(err.stderr) : '') + '\n' + ((err && err.message) || '');
      if (/externally-managed-environment|PEP ?668|break-system-packages/i.test(msg)) {
        try {
          await execFileP(py, ['-m', 'pip', 'install', '--user', '--break-system-packages', 'pipx'], BIG);
          installed = true;
        } catch { /* give up on pip bootstrap */ }
      }
    }
  }
  if (!installed) return false;
  // Wire the new pipx onto PATH for this session.
  try { await execFileP(py || 'python3', ['-m', 'pipx', 'ensurepath'], { timeout: 30000 }); } catch {}
  try { require('../bootstrap/app-events').refreshSpawnPath(); } catch {}
  try { await execFileP('pipx', ['--version'], { timeout: 10000 }); return true; }
  catch { return false; }
}

function ensureReviewTools() {
  if (toolsPromise) return toolsPromise;
  toolsPromise = (async () => {
    // GUI launches start with a minimal PATH, so pipx/uv/python may be invisible
    // even though they're installed. Refresh PATH from the user's shell first so
    // both tool detection and installer selection can see them.
    try { require('../bootstrap/app-events').refreshSpawnPath(); } catch {}

    const missing = [];
    for (const t of TOOLS) if (!(await toolPresent(t.cmd))) missing.push(t);
    if (!missing.length) return true;
    const pkgs = missing.map((t) => t.pkg);

    let installer = await pickInstaller();
    if (!installer) {
      // Nothing we can do automatically. Report it (without handing the user a
      // command to run) and clear the memo so a later trigger can retry once an
      // installer is present.
      console.warn('[repo-intel] cannot auto-install', pkgs.join(', '), '— no pipx, uv, or pip found');
      notifyWindows({ type: 'tools-failed', missing: pkgs, reason: 'no Python installer (pipx/uv/pip) available' });
      toolsPromise = null;
      return false;
    }
    // Only bare pip available (no isolated installer) — bootstrap pipx for the
    // user in the background and prefer it, so the tools land in clean venvs
    // instead of leaning on pip's PEP 668 escape hatch. Falls back to pip if the
    // bootstrap doesn't take.
    if (installer.kind === 'pip' && await bootstrapPipx(installer.py)) {
      console.log('[repo-intel] bootstrapped pipx');
      installer = { kind: 'pipx' };
    }

    notifyWindows({ type: 'tools-installing', missing: pkgs, installer: installer.kind });
    console.log('[repo-intel] installing', pkgs.join(', '), 'via', installer.kind);
    // Separate installs so one tool's failure doesn't abort the others — the
    // post-install availability re-check below owns the overall verdict.
    const BIG = { timeout: 5 * 60 * 1000, maxBuffer: 16 * 1024 * 1024 };
    const installOne = async (pkg) => {
      if (installer.kind === 'pipx') return execFileP('pipx', ['install', pkg], BIG);
      if (installer.kind === 'uv') return execFileP('uv', ['tool', 'install', pkg], BIG);
      // pip --user. An externally-managed Python (PEP 668, e.g. Homebrew) refuses
      // the plain install; retry once with --break-system-packages — the
      // documented escape hatch, safe here since --user can't touch system pkgs.
      try {
        return await execFileP(installer.py, ['-m', 'pip', 'install', '--user', pkg], BIG);
      } catch (err) {
        const msg = (err && err.stderr ? String(err.stderr) : '') + '\n' + ((err && err.message) || '');
        if (/externally-managed-environment|PEP ?668|break-system-packages/i.test(msg)) {
          return execFileP(installer.py, ['-m', 'pip', 'install', '--user', '--break-system-packages', pkg], BIG);
        }
        throw err;
      }
    };
    const failures = [];
    for (const t of missing) {
      try {
        await installOne(t.pkg);
      } catch (err) {
        const first = ((err && err.stderr ? String(err.stderr) : '') || (err && err.message) || '').trim().split('\n').pop();
        console.warn('[repo-intel] install failed for', t.pkg + ':', first);
        failures.push(first);
      }
    }

    // New binaries land in ~/.local/bin (pipx) or the pip user bin — make
    // them findable in this session without a restart.
    try { require('../bootstrap/app-events').refreshSpawnPath(); } catch {}
    // Drop the cached "missing" klaussy CLI so the next ensure re-probes.
    klaussyCli = { bin: null, version: null, at: 0, promise: null };

    const ok = (await Promise.all(missing.map((t) => toolPresent(t.cmd)))).every(Boolean);
    if (ok) {
      console.log('[repo-intel] installed', pkgs.join(', '));
      notifyWindows({ type: 'tools-installed', installed: pkgs });
    } else {
      // Don't hand the user a manual command — just surface that the background
      // install didn't take, and clear the memo so the next trigger retries.
      const reason = failures.length ? failures[failures.length - 1] : 'installed but not on PATH';
      console.warn('[repo-intel] auto-install incomplete:', reason);
      notifyWindows({ type: 'tools-failed', missing: pkgs, reason });
      toolsPromise = null;
    }
    return ok;
  })();
  return toolsPromise;
}

// Once a day, upgrade the analysis CLIs to their latest release so users keep
// getting new skills/templates. ensureRepoIntel is version-gated, so a CLI
// version bump makes the next intel run regenerate each repo's skills. Daily
// gate (config.reviewToolsCheckedAt) keeps this off the every-boot hot path;
// best-effort and fully background — never blocks or surfaces failures.
const TOOLS_UPGRADE_INTERVAL_MS = 24 * 60 * 60 * 1000;
async function upgradeReviewToolsIfDue() {
  try {
    const cfg = loadConfig();
    if (Date.now() - (cfg.reviewToolsCheckedAt || 0) < TOOLS_UPGRADE_INTERVAL_MS) return;
    try { require('../bootstrap/app-events').refreshSpawnPath(); } catch {}
    const installer = await pickInstaller();
    if (!installer) return;
    const BIG = { timeout: 5 * 60 * 1000, maxBuffer: 16 * 1024 * 1024 };
    for (const t of TOOLS) {
      const pkg = t.pkg;
      try {
        if (installer.kind === 'pipx') {
          await execFileP('pipx', ['upgrade', pkg], BIG);
        } else if (installer.kind === 'uv') {
          await execFileP('uv', ['tool', 'upgrade', pkg], BIG);
        } else {
          try {
            await execFileP(installer.py, ['-m', 'pip', 'install', '--user', '-U', pkg], BIG);
          } catch (err) {
            const msg = (err && err.stderr ? String(err.stderr) : '') + '\n' + ((err && err.message) || '');
            if (/externally-managed-environment|PEP ?668|break-system-packages/i.test(msg)) {
              await execFileP(installer.py, ['-m', 'pip', 'install', '--user', '-U', '--break-system-packages', pkg], BIG);
            }
          }
        }
      } catch (e) {
        // A single tool failing to upgrade (already latest, offline, etc.) is fine.
        console.warn('[repo-intel] upgrade skipped for', pkg + ':', (e && e.message) || e);
      }
    }
    const c2 = loadConfig();
    c2.reviewToolsCheckedAt = Date.now();
    saveConfig(c2);
    // A new CLI version invalidates the cached intel — bust the version cache so
    // the next ensureRepoIntel regenerates skills with the upgraded templates.
    klaussyCli = { bin: null, version: null, at: 0, promise: null };
    try { require('../bootstrap/app-events').refreshSpawnPath(); } catch {}
    console.log('[repo-intel] checked analysis tools for upgrades');
  } catch (e) {
    console.warn('[repo-intel] upgrade check failed:', (e && e.message) || e);
  }
}

// Resolve a worktree (or repo) path to its primary checkout — intel belongs
// to the base repo and is shared by every worktree/session under it.
// Memoized: the mapping is immutable for a given path, and the underlying
// `git rev-parse` is a blocking subprocess we don't want on every prompt
// build / IPC call.
function baseFor(repoOrWorktreePath) {
  if (!repoOrWorktreePath) return null;
  if (baseCache.has(repoOrWorktreePath)) return baseCache.get(repoOrWorktreePath);
  const base = baseRepoForWorktree(repoOrWorktreePath) || repoOrWorktreePath;
  baseCache.set(repoOrWorktreePath, base);
  return base;
}

// klaussy init prompts interactively for the base branch unless -b is
// passed — resolve it the same way create-task does.
function defaultBranchOf(repoPath) {
  try {
    return execFileSync('git', ['symbolic-ref', 'refs/remotes/origin/HEAD', '--short'], {
      cwd: repoPath, stdio: 'pipe',
    }).toString().trim().replace(/^origin\//, '');
  } catch { /* no origin/HEAD — probe the usual names */ }
  for (const c of ['main', 'master', 'dev', 'develop']) {
    try {
      execFileSync('git', ['rev-parse', '--verify', c], { cwd: repoPath, stdio: 'pipe' });
      return c;
    } catch { /* try next */ }
  }
  return 'main';
}

// The agent bootstrap klaussy generates is scaffolding, not source — it
// shouldn't land in users' commits/PRs. Every time we make it, add it to the
// repo's LOCAL .git/info/exclude (per-clone, never touches the team's tracked
// .gitignore). Note: info/exclude only keeps UNTRACKED files out — a file a
// repo already committed (e.g. a hand-authored CLAUDE.md) stays tracked; we
// don't forcibly `git rm --cached` it, since staging deletions of the user's
// committed files would be destructive. For a worktree this writes to the
// shared common git dir, so the base repo and every sibling worktree inherit it.
const BOOTSTRAP_EXCLUDE_MARKER = '# klaussy: agent bootstrap (generated, not committed)';
const BOOTSTRAP_EXCLUDES = [
  '.claude/', '.codex/', '.cursor/', '.gemini/',
  '.github/skills/', '.github/hooks/',   // leave .github/workflows alone
  '.conventions/',
  'CLAUDE.md', 'CLAUDE.local.md', 'AGENTS.md', 'GEMINI.md',
];
function excludeBootstrapArtifacts(repoOrWorktreePath) {
  try {
    let common = execFileSync('git', ['rev-parse', '--git-common-dir'], {
      cwd: repoOrWorktreePath, stdio: 'pipe',
    }).toString().trim();
    if (!path.isAbsolute(common)) common = path.resolve(repoOrWorktreePath, common);
    const excludePath = path.join(common, 'info', 'exclude');
    let existing = '';
    try { existing = fs.readFileSync(excludePath, 'utf-8'); } catch { /* no exclude yet */ }
    if (existing.includes(BOOTSTRAP_EXCLUDE_MARKER)) return; // idempotent
    fs.mkdirSync(path.dirname(excludePath), { recursive: true });
    const block = '\n' + BOOTSTRAP_EXCLUDE_MARKER + '\n' + BOOTSTRAP_EXCLUDES.join('\n') + '\n';
    fs.appendFileSync(excludePath, (existing && !existing.endsWith('\n') ? '\n' : '') + block);
  } catch (e) {
    console.warn('[repo-intel] bootstrap exclude failed for', repoOrWorktreePath + ':', (e && e.message) || e);
  }
}

// Make the base repo's env files available in a worktree so nobody has to copy
// `.env` around. Worktrees only contain COMMITTED files, and env files are
// gitignored, so they're missing — which is why agents (and dev servers/tests
// that load ./.env) can't find them. We SYMLINK rather than copy: the base repo
// stays the single source of truth, edits propagate, and nothing drifts.
// Covers monorepo subdir env files (src/server/.env, etc.) via `git ls-files
// --ignored`. Skips node_modules, committed example files, and anything the
// worktree already has (e.g. a manual copy). Falls back to a copy if symlinks
// aren't permitted (Windows without privilege). The symlinks are gitignored by
// the repo's own .gitignore, so they never get committed.
function linkEnvFilesIntoWorktree(base, worktreePath) {
  let listed = '';
  try {
    listed = execFileSync('git', ['-C', base, 'ls-files', '--others', '--ignored', '--exclude-standard', '-z'], {
      maxBuffer: 8 * 1024 * 1024,
    }).toString();
  } catch { return; }
  // Match common env-file conventions by basename: `.env`, `.env.<x>`, the
  // direnv `.envrc`, and suffix forms like `secrets.env` / `local.env`. Skip
  // the obvious non-secret templates.
  const isEnvName = (p) => {
    const b = p.split('/').pop();
    if (/\.(example|sample|template|dist)$/i.test(b)) return false;
    return b === '.env' || b.startsWith('.env.') || b === '.envrc' || /\.env$/.test(b);
  };
  const rels = listed.split('\0').filter(Boolean).filter((p) =>
    isEnvName(p) && !/(^|\/)node_modules\//.test(p));
  for (const rel of rels) {
    const src = path.join(base, rel);
    const dst = path.join(worktreePath, rel);
    try { if (!fs.statSync(src).isFile()) continue; } catch { continue; }
    // lstat (not existsSync) so a pre-existing symlink/file — including a manual
    // copy — is respected and never clobbered.
    try { fs.lstatSync(dst); continue; } catch { /* missing — create it */ }
    try {
      fs.mkdirSync(path.dirname(dst), { recursive: true });
      fs.symlinkSync(src, dst);
    } catch {
      try { fs.copyFileSync(src, dst); } catch (e) {
        console.warn('[repo-intel] env link/copy failed for', rel + ':', (e && e.message) || e);
      }
    }
  }
}

// Symlink the base repo's env files into a worktree, resolving the base
// itself. Decoupled from intel generation so spawn paths can call it directly
// and env is present the moment the agent starts — even if repo-intel is
// uninstalled, mid-generation, or backed off after a failure. Idempotent and
// best-effort. (The bigger syncIntelIntoWorktree below also calls it.)
function ensureEnvLinks(worktreePath) {
  try {
    const base = baseFor(worktreePath);
    if (base && base !== worktreePath) linkEnvFilesIntoWorktree(base, worktreePath);
  } catch (e) {
    console.warn('[repo-intel] env link failed for', worktreePath + ':', (e && e.message) || e);
  }
}

// Copy the base repo's intel artifacts into a worktree that lacks them.
// Worktrees only materialize COMMITTED files; until the user commits
// CLAUDE.md & co., interactive agents in the worktree would see nothing
// ("no CLAUDE.md provided"). Copies only what's missing, so committed
// versions and per-worktree settings.local.json are never touched.
function syncIntelIntoWorktree(worktreePath) {
  try {
    const base = baseFor(worktreePath);
    if (!base || base === worktreePath) return;
    // klaussy init scaffolds each supported agent under its own root
    // (.claude / .codex / .cursor / .gemini / .github), with skills, slash
    // commands, rules, and hooks inside. Sync every agent's equivalents so the
    // worktree the agent actually runs in has them — whichever agent the user
    // picks. Skills/commands not synced here are simply missing from the
    // terminal (the original bug: commands lived only in the base repo).
    const AGENT_ROOTS = ['.claude', '.codex', '.cursor', '.gemini', '.github'];
    // hooks MUST travel with settings.json: settings register PreToolUse hooks
    // by relative path; a worktree with the settings but not the scripts blocks
    // every Read/Bash call (missing hook exits 2 = deny).
    const AGENT_SUBS = ['skills', 'commands', 'rules', 'hooks'];
    const entries = [['CLAUDE.md'], ['.claude', 'settings.json']];
    for (const root of AGENT_ROOTS) {
      for (const sub of AGENT_SUBS) entries.push([root, sub]);
    }
    // Recursively copy any child of src that's missing in dst. Used for the
    // .claude/* directories so skills/commands ADDED to the base after the
    // worktree was created still land — a directory-level existence check
    // would skip the whole dir and strand every new skill/command. Never
    // overwrites an existing worktree file (preserves local edits).
    const copyMissing = (src, dst) => {
      if (fs.statSync(src).isDirectory()) {
        fs.mkdirSync(dst, { recursive: true });
        for (const child of fs.readdirSync(src)) copyMissing(path.join(src, child), path.join(dst, child));
      } else if (!fs.existsSync(dst)) {
        fs.mkdirSync(path.dirname(dst), { recursive: true });
        fs.cpSync(src, dst);
      }
    };
    for (const segs of entries) {
      const src = path.join(base, ...segs);
      const dst = path.join(worktreePath, ...segs);
      if (!fs.existsSync(src)) continue;
      const leaf = segs[segs.length - 1];
      if (leaf === 'CLAUDE.md') {
        try {
          if (fs.readFileSync(src, 'utf-8') === CLAUDE_MD_PLACEHOLDER) continue;
        } catch { continue; }
        // A previous sync may have raced an unfinished generation and seeded
        // the placeholder — repair it; otherwise never overwrite.
        if (fs.existsSync(dst)) {
          try {
            if (fs.readFileSync(dst, 'utf-8') !== CLAUDE_MD_PLACEHOLDER) continue;
          } catch { continue; }
        }
        fs.mkdirSync(path.dirname(dst), { recursive: true });
        fs.cpSync(src, dst);
      } else if (leaf === 'settings.json') {
        if (fs.existsSync(dst)) {
          // Never clobber a worktree's settings, but merge in any klaussy-managed
          // hooks it's missing (e.g. a hook the base gained after this worktree
          // was created) so they actually register here. Add-only; local edits
          // and custom hooks are preserved.
          mergeMissingHooksIntoWorktree(src, dst);
          continue;
        }
        fs.mkdirSync(path.dirname(dst), { recursive: true });
        fs.cpSync(src, dst);
      } else {
        // .claude/{rules,skills,commands,hooks}: merge in missing children.
        copyMissing(src, dst);
      }
    }
    // Heal a stale klausify-era settings.json — whether just copied from a
    // not-yet-repaired base or already present in this worktree (the copy loop
    // skips existing files, so an old bad one would otherwise survive).
    repairClaudeSettings(worktreePath);
    // Keep the freshly-synced bootstrap out of commits.
    excludeBootstrapArtifacts(worktreePath);
    // Symlink the base repo's env files in so nobody has to copy .env around.
    linkEnvFilesIntoWorktree(base, worktreePath);
  } catch (e) {
    console.warn('[repo-intel] worktree sync failed for', worktreePath, e.message);
  }
}

// After (re)generation, push the artifacts into every live worktree of this
// base repo — sessions are usually created BEFORE the analysis finishes.
function syncIntelIntoActiveWorktrees(base) {
  try {
    // Ignore the bootstrap we just generated in the base repo itself (covers
    // the no-worktree case; worktree syncs below hit the shared exclude too).
    excludeBootstrapArtifacts(base);
    const { instances } = require('./instances');
    for (const [, inst] of instances) {
      if (inst && inst.worktreePath && baseFor(inst.worktreePath) === base) {
        syncIntelIntoWorktree(inst.worktreePath);
      }
    }
  } catch (e) {
    console.warn('[repo-intel] active-worktree sync failed:', e.message);
  }
}

function loadStructuredIntel(basePath) {
  const a = artifactPaths(basePath);
  let claudeMd = '';
  if (fs.existsSync(a.claudeMd)) {
    let md = fs.readFileSync(a.claudeMd, 'utf-8').trim();
    if (md && md !== CLAUDE_MD_PLACEHOLDER.trim()) {
      if (md.length > CLAUDE_MD_CAP) md = md.slice(0, CLAUDE_MD_CAP) + '\n…(truncated — full file at CLAUDE.md)';
      claudeMd = md;
    }
  }

  const rules = [];
  if (fs.existsSync(a.rulesDir)) {
    for (const f of fs.readdirSync(a.rulesDir).filter((x) => x.endsWith('.md')).sort()) {
      try {
        const content = fs.readFileSync(path.join(a.rulesDir, f), 'utf-8').trim();
        rules.push({ file: f, content });
      } catch {
        continue;
      }
    }
  }

  let graphRules = [];
  try {
    if (fs.existsSync(a.rawJson)) {
      const data = JSON.parse(fs.readFileSync(a.rawJson, 'utf-8'));
      graphRules = Array.isArray(data.rules) ? data.rules : [];
    }
  } catch (e) {
    console.warn('[repo-intel] failed to load rawJson:', e.message);
  }

  return { claudeMd, rules, graphRules };
}

function ruleMatchesTouchedPaths(ruleFileName, touchedPaths) {
  if (!touchedPaths || touchedPaths.length === 0) return true;
  const ruleName = ruleFileName.replace(/\.md$/i, '').toLowerCase();
  for (const p of touchedPaths) {
    const norm = p.toLowerCase().replace(/\\/g, '/');
    const segments = norm.split('/');
    if (segments.includes(ruleName) || norm.includes('/' + ruleName) || norm.startsWith(ruleName)) {
      return true;
    }
  }
  return false;
}

function filterGraphSummary(graphRules, touchedPaths) {
  if (!graphRules || graphRules.length === 0) return null;
  const lines = [];
  const fanList = (list) => list
    .map((e) => (Array.isArray(e) && e.length >= 2 ? `${e[0]} (${e[1]})` : null))
    .filter(Boolean)
    .join(', ');

  const hasTouchedPaths = touchedPaths && touchedPaths.length > 0;

  try {
    for (const r of graphRules) {
      if (!r || typeof r.id !== 'string') continue;
      if (/\.import_graph$/.test(r.id)) {
        let statsPrinted = false;
        const s = r.stats || {};
        
        if (Array.isArray(s.top_fan_in) && s.top_fan_in.length) {
          const filteredFanIn = hasTouchedPaths
            ? s.top_fan_in.filter(([file]) => {
                const normFile = file.toLowerCase().replace(/\\/g, '/');
                return touchedPaths.some(p => {
                  const normP = p.toLowerCase().replace(/\\/g, '/');
                  return normP.endsWith(normFile) || normFile.endsWith(normP);
                });
              })
            : s.top_fan_in;

          if (filteredFanIn.length) {
            const t = fanList(filteredFanIn);
            if (t) {
              lines.push('- Most-depended-on files (fan-in — changes here have wide blast radius): ' + t);
              statsPrinted = true;
            }
          }
        }

        if (Array.isArray(s.top_fan_out) && s.top_fan_out.length) {
          const filteredFanOut = hasTouchedPaths
            ? s.top_fan_out.filter(([file]) => {
                const normFile = file.toLowerCase().replace(/\\/g, '/');
                return touchedPaths.some(p => {
                  const normP = p.toLowerCase().replace(/\\/g, '/');
                  return normP.endsWith(normFile) || normFile.endsWith(normP);
                });
              })
            : s.top_fan_out;

          if (filteredFanOut.length) {
            const t = fanList(filteredFanOut);
            if (t) {
              lines.push('- Widest-reaching files (fan-out): ' + t);
              statsPrinted = true;
            }
          }
        }

        if (s.cycle_count) {
          lines.push(`- WARNING: ${s.cycle_count} circular dependency chain(s) exist — do not introduce new edges into them.`);
          statsPrinted = true;
        }

        if (statsPrinted && r.description) {
          lines.unshift('- ' + r.description);
        }
      } else if (/endpoint_chains|service_dependencies|\.data_flow\./.test(r.id) && r.description) {
        if (hasTouchedPaths) {
          const matches = touchedPaths.some(p => {
            const baseName = p.split('/').pop().replace(/\.[^.]+$/, '');
            return r.description.toLowerCase().includes(baseName.toLowerCase()) || r.id.toLowerCase().includes(baseName.toLowerCase());
          });
          if (matches) lines.push('- ' + r.description);
        } else {
          lines.push('- ' + r.description);
        }
      }
    }
  } catch (e) {
    console.warn('[repo-intel] graph summary filtering failed:', e.message);
    if (!lines.length) return null;
  }
  if (!lines.length) return null;
  return '### Code graph (import/dependency analysis)\n\n' + lines.join('\n')
    + '\n\nWhen reviewing or planning changes to a high fan-in file, consider its dependents — regressions there ripple widest.';
}

function assembleBlock(intel, touchedPaths = []) {
  const parts = [];

  if (intel.claudeMd) {
    parts.push('### Repository conventions (CLAUDE.md)\n\n' + intel.claudeMd);
  }

  if (intel.rules && intel.rules.length > 0) {
    const chunks = [];
    let budget = RULES_CAP;
    const filteredRules = intel.rules.filter(r => ruleMatchesTouchedPaths(r.file, touchedPaths));

    for (const r of filteredRules) {
      if (r.content.length > budget) {
        chunks.push(`- Additional path-scoped rules in .claude/rules/${r.file} (read it when touching matching paths)`);
        continue;
      }
      budget -= r.content.length;
      chunks.push(`#### .claude/rules/${r.file}\n\n${r.content}`);
    }
    if (chunks.length) parts.push('### Path-scoped rules\n\n' + chunks.join('\n\n'));
  }

  const graph = filterGraphSummary(intel.graphRules, touchedPaths);
  if (graph) parts.push(graph);

  return parts.length
    ? '## Repository intelligence\n\n'
      + 'Auto-generated from this repository (klaussy-agents / klaussy-repo-conventions). Treat these conventions, rules, and graph facts as ground truth for this codebase; flag violations of them explicitly.\n\n'
      + parts.join('\n\n')
    : '';
}

function buildBlock(basePath, cliVersion) {
  try {
    const srcMtime = artifactsMtime(basePath);
    const intel = loadStructuredIntel(basePath);
    const block = assembleBlock(intel);

    const ver = cliVersion !== undefined
      ? cliVersion
      : ((memCache.get(basePath) || {}).cliVersion || '');
    memCache.set(basePath, { block, intel, srcMtime, cliVersion: ver });
    try {
      const f = cacheFileFor(basePath);
      if (block) {
        fs.mkdirSync(path.dirname(f), { recursive: true });
        fs.writeFileSync(f, '<!-- src-mtime:' + srcMtime + ' cli:' + ver + ' -->\n' + block);
      } else {
        fs.rmSync(f, { force: true });
      }
    } catch {}
    return block;
  } catch (e) {
    console.warn('[repo-intel] block build failed for', basePath, e.message);
    return '';
  }
}

function readDiskCache(basePath) {
  try {
    const f = cacheFileFor(basePath);
    if (!fs.existsSync(f)) return null;
    const raw = fs.readFileSync(f, 'utf-8');
    const m = raw.match(/^<!-- src-mtime:([\d.]+)(?: cli:([^>]*))? -->\n/);
    if (!m) return null;
    return { block: raw.slice(m[0].length), srcMtime: Number(m[1]), cliVersion: (m[2] || '').trim() };
  } catch {
    return null;
  }
}

// Unlink raw.json when it doesn't parse — a CLI run killed by the timeout
// can leave a truncated file whose fresh mtime would otherwise vouch for it
// for a week.
function validateRawJson(basePath) {
  const p = artifactPaths(basePath).rawJson;
  if (!fs.existsSync(p)) return;
  try {
    JSON.parse(fs.readFileSync(p, 'utf-8'));
  } catch {
    console.warn('[repo-intel] removing corrupt conventions.raw.json in', basePath);
    try { fs.rmSync(p, { force: true }); } catch {}
  }
}

// Fire-and-forget: make sure the base repo has fresh analysis artifacts,
// regenerating when missing, stale, or built by an older klaussy version.
// Single-flight per repo. Never throws.
function ensureRepoIntel(repoOrWorktreePath) {
  let base;
  try {
    base = baseFor(repoOrWorktreePath);
    if (!base || !fs.existsSync(path.join(base, '.git'))) return Promise.resolve();
  } catch {
    return Promise.resolve();
  }
  if (inflight.has(base)) return inflight.get(base);
  // A repo that just failed (CLI missing, scan error) must not restart the
  // whole pipeline — with its started/failed toast pair — on every prompt
  // build. Back off, then retry naturally.
  const lastFail = failedAt.get(base);
  if (lastFail && Date.now() - lastFail < FAIL_BACKOFF_MS) return Promise.resolve();

  const p = (async () => {
    try {
      // First-run: make sure the analysis CLIs exist (auto-installs from
      // PyPI if not). Cheap when already present. If install fails the
      // generation below degrades to whatever artifacts exist.
      // `firstToolsCall` = were WE the caller that actually ran (and toasted)
      // the install? ensureReviewTools is single-flight, so only the first
      // caller's await emits the tools-failed toast; later repos get the
      // cached result silently. The gate below uses this to decide whether a
      // per-repo "unavailable" toast is needed or would just duplicate.
      const firstToolsCall = !toolsPromise;
      const toolsOk = await ensureReviewTools();
      const cli = await getKlaussyCli();
      const currentVersion = cli.version || '';
      const a = artifactPaths(base);
      // Heal a stale klausify-era settings.json on the base repo every run
      // (cache hit or full regen) — klaussy init won't, since it skips existing
      // files. Cheap and idempotent: a clean settings.json is a no-op.
      repairClaudeSettings(base);
      const srcMtime = artifactsMtime(base);
      const cached = memCache.get(base) || readDiskCache(base);
      const stampedVersion = cached ? (cached.cliVersion || '') : null;

      const haveArtifacts = fs.existsSync(a.rawJson);
      const freshEnough = haveArtifacts && (Date.now() - srcMtime < STALE_MS);
      const sameVersion = stampedVersion !== null && stampedVersion === currentVersion;

      if (freshEnough && sameVersion) {
        // Nothing to regenerate — but keep caches coherent, sync worktrees,
        // and STILL tell the user (silent cache hits read as "nothing ran").
        if (!memCache.has(base) || memCache.get(base).srcMtime < srcMtime) {
          buildBlock(base, currentVersion);
        }
        syncIntelIntoActiveWorktrees(base);
        // Announce the cache hit once per repo per app run — evidence
        // without a toast on every single session create.
        if (!freshNotified.has(base)) {
          freshNotified.add(base);
          notifyWindows({ type: 'fresh', repoPath: base });
        }
        return;
      }

      // About to (re)generate — pass 1 unconditionally spawns the `conventions`
      // CLI (the klaussy spawn below is separately guarded by currentVersion,
      // so it can't ENOENT). If conventions isn't reachable (install failed, or
      // installed somewhere not on the GUI's PATH), spawning it throws
      // `spawn conventions ENOENT`. Probe first and degrade to whatever
      // artifacts exist instead of crashing into ENOENT.
      const haveConventions = toolsOk || (await toolPresent('conventions'));
      if (!haveConventions) {
        console.warn('[repo-intel] conventions CLI unavailable — skipping generation for', base);
        buildBlock(base, ''); // use a committed CLAUDE.md/graph if present
        syncIntelIntoActiveWorktrees(base);
        failedAt.set(base, Date.now()); // back off; retry naturally later
        // Per-repo signal so a 2nd+ repo in a session still gets feedback: the
        // global tools-failed toast fires only once per app run. Suppress it
        // only for the repo whose own ensureReviewTools call just emitted
        // tools-failed, to avoid a duplicate toast on that same failure.
        if (!firstToolsCall) {
          notifyWindows({ type: 'failed', repoPath: base, error: 'analysis tools not reachable on PATH (ENOENT)' });
        }
        return;
      }

      // "enriching" only when klaussy is present AND the user opted into the
      // billed Claude rewrite — drives the toast's "may take a few minutes".
      notifyWindows({ type: 'started', repoPath: base, enriching: !!currentVersion && loadConfig().repoIntelEnrich === true });

      // Pass 1 — graph data: always safe (writes only .conventions/).
      await execFileP('conventions', ['discover', '--format', 'json', '-q'], {
        cwd: base,
        timeout: 5 * 60 * 1000,
        maxBuffer: 16 * 1024 * 1024,
      });
      validateRawJson(base);

      // Make the fast parts available immediately: the import graph (and any
      // existing CLAUDE.md/rules) reach prompts within seconds, instead of
      // waiting minutes for the Claude enrichment on large repos. The
      // enriched block replaces this one when pass 2 finishes. Explicit ''
      // stamp = "no completed run" — only a fully successful pass 2 stamps
      // the version, so failures retry instead of looking done.
      buildBlock(base, '');
      syncIntelIntoActiveWorktrees(base);

      let wroteSkills = false;
      let enrichFailed = false;
      if (currentVersion) {
        // Pass 2a — klaussy init: CLAUDE.md + rules + conventions-aware
        // skills + settings. No --force, so existing files (handcrafted
        // CLAUDE.md, customized skills) are preserved. -b is mandatory to
        // keep it non-interactive.
        //
        // Enrichment (the Claude pass that rewrites CLAUDE.md into richer
        // prose) invokes the claude CLI = real API spend on the user's
        // machine. Off by default; --skip-enrich still produces the full
        // skills/rules/settings + a templated CLAUDE.md, just without the
        // LLM rewrite.
        const enrich = loadConfig().repoIntelEnrich === true;
        const initArgs = ['init', '--repo', base, '-b', defaultBranchOf(base)];
        if (!enrich) initArgs.push('--skip-enrich');
        //
        // Guard: klaussy's exists-check → write window isn't atomic (it
        // even runs a pip upgrade in between). Snapshot a pre-existing
        // CLAUDE.md and restore it if the run somehow replaced it.
        let preClaudeMd = null;
        try { preClaudeMd = fs.readFileSync(a.claudeMd, 'utf-8'); } catch { /* absent */ }
        const { stdout: initOut } = await execFileP(cli.bin, initArgs, {
          timeout: 15 * 60 * 1000, // enrichment invokes the claude CLI
          maxBuffer: 16 * 1024 * 1024,
        });
        if (preClaudeMd !== null) {
          try {
            if (fs.readFileSync(a.claudeMd, 'utf-8') !== preClaudeMd) {
              console.warn('[repo-intel] klaussy replaced a pre-existing CLAUDE.md — restoring it');
              fs.writeFileSync(a.claudeMd, preClaudeMd);
            }
          } catch { /* deleted mid-run — leave whatever exists */ }
        }
        // klaussy's hook scaffold is version-gated (like its skills): the
        // force-less `init` above re-installs hooks whenever the CLI version
        // changed, so an already-initialized repo picks up newly-added hooks
        // (e.g. pre-plan guidance) automatically on upgrade — no --force needed.
        // klaussy-repo-conventions swallows enrichment failures (claude missing /
        // unauthenticated / timeout) into a stdout warning and exits 0 —
        // detect it so we don't stamp the run as complete and toast success
        // over an unenriched CLAUDE.md.
        enrichFailed = /could not enrich/i.test(String(initOut || ''));
        wroteSkills = true;
      } else {
        // Pass 2b — fallback without klaussy: conventions claude format.
        // That CLI overwrites CLAUDE.md unconditionally, so only run it
        // after atomically claiming the path (`wx` fails if the file exists
        // or appears between checks — e.g. the user ran /init in the
        // freshly spawned session).
        let claimed = false;
        try {
          fs.writeFileSync(a.claudeMd, CLAUDE_MD_PLACEHOLDER, { flag: 'wx' });
          claimed = true;
        } catch { /* CLAUDE.md exists — never let the CLI touch it */ }
        if (claimed) {
          try {
            await execFileP('conventions', ['discover', '--format', 'claude', '-q'], {
              cwd: base,
              timeout: 5 * 60 * 1000,
              maxBuffer: 16 * 1024 * 1024,
            });
          } finally {
            try {
              if (fs.readFileSync(a.claudeMd, 'utf-8') === CLAUDE_MD_PLACEHOLDER) {
                fs.rmSync(a.claudeMd, { force: true });
              }
            } catch {}
          }
        }
      }

      // Stamp the version only on a fully completed run — an enrichment
      // failure leaves the '' stamp so the next session retries.
      buildBlock(base, enrichFailed ? '' : currentVersion);
      syncIntelIntoActiveWorktrees(base);
      failedAt.delete(base);
      console.log('[repo-intel] generated for', base,
        wroteSkills ? (enrichFailed ? '(klaussy init, enrichment FAILED)' : '(klaussy init + graph)') : '(conventions fallback)');
      notifyWindows({ type: 'generated', repoPath: base, wroteSkills, enrichFailed });
    } catch (err) {
      const first = ((err && err.stderr ? String(err.stderr) : '') || (err && err.message) || '').trim().split('\n')[0];
      console.warn('[repo-intel] generation failed for', base + ':', first);
      failedAt.set(base, Date.now());
      notifyWindows({ type: 'failed', repoPath: base, error: first });
      validateRawJson(base);
      // Still build from whatever artifacts exist (e.g. a committed
      // CLAUDE.md) — '' stamp so the backoff, not the cache, owns the retry.
      buildBlock(base, '');
      syncIntelIntoActiveWorktrees(base);
    } finally {
      inflight.delete(base);
    }
  })();
  inflight.set(base, p);
  return p;
}

// Slim variant for Claude agents running inside a synced worktree: the
// claude CLI loads CLAUDE.md + .claude/rules from the worktree natively (and
// caches that prefix across turns), so re-injecting them into every prompt
// would pay their tokens twice. The import graph is the only section
// CLAUDE.md doesn't carry.
function slimFromBlock(block) {
  if (!block) return '';
  const idx = block.indexOf('### Code graph');
  if (idx === -1) return ''; // nothing CLAUDE.md doesn't already provide
  return '## Repository intelligence\n\n'
    + 'This worktree carries the repo conventions natively (CLAUDE.md + .claude/rules, loaded automatically — treat them as ground truth and flag violations).\n\n'
    + block.slice(idx);
}

// The cached prompt block for a repo/worktree ('' when nothing is available
// yet — prompt builders append it conditionally). Coherent with on-disk
// artifacts: any cache built from older artifacts is rebuilt here.
//
// `agentMode`: pass the agent the prompt targets. For 'claude' with a
// CLAUDE.md present at the queried path (i.e. a synced worktree), the slim
// graph-only block is returned — token saving, see slimFromBlock. Other
// agents (codex/gemini/copilot don't read CLAUDE.md) and unsynced paths get
// the full block.
//
// `touchedPaths`: optional list of files touched in the current PR or task.
// If provided, we generate a minimized block tailored to these paths.
function getRepoIntelBlock(repoOrWorktreePath, agentMode, touchedPaths = []) {
  let base;
  try {
    base = baseFor(repoOrWorktreePath);
  } catch {
    return '';
  }
  if (!base) return '';
  const srcMtime = artifactsMtime(base);

  let hit = memCache.get(base);
  if (!hit || hit.srcMtime < srcMtime) {
    const disk = readDiskCache(base);
    if (disk && disk.srcMtime >= srcMtime) {
      const intel = loadStructuredIntel(base);
      hit = { block: disk.block, intel, srcMtime, cliVersion: disk.cliVersion };
      memCache.set(base, hit);
    } else {
      buildBlock(base);
      hit = memCache.get(base);
    }
  }

  if (!hit) return '';

  const block = (touchedPaths && touchedPaths.length > 0 && hit.intel)
    ? assembleBlock(hit.intel, touchedPaths)
    : hit.block;

  if (!block) return '';

  if (agentMode === 'claude') {
    try {
      if (fs.existsSync(path.join(repoOrWorktreePath, 'CLAUDE.md'))) {
        return slimFromBlock(block);
      }
    } catch { /* fall through to full */ }
  }
  return block;
}

// Ensure a worktree that Klaussy didn't create through the normal session path
// (e.g. a PR-review worktree, which is cloned/fetched separately and never
// enters the `instances` map that syncIntelIntoActiveWorktrees iterates) still
// gets the agent bootstrap that lives only in the base repo: skills, slash
// commands, rules, hooks, CLAUDE.md, settings. Without this the review agent
// can't find project skills/commands — a worktree contains only committed
// files. Kicks generation for next time and copies whatever exists now.
// Best-effort: never throws, never blocks the caller's spawn.
function ensureWorktreeBootstrap(worktreePath) {
  // Generate/refresh the base repo's artifacts in the background (cache-hit
  // fast; first run may install CLIs, so don't await it on the spawn path).
  try {
    const p = ensureRepoIntel(worktreePath);
    if (p && typeof p.catch === 'function') p.catch((e) => console.warn('[repo-intel] bootstrap ensure failed:', e && e.message));
  } catch (e) { console.warn('[repo-intel] bootstrap ensure failed:', e && e.message); }
  // Copy whatever bootstrap already exists in the base repo into this worktree.
  try { syncIntelIntoWorktree(worktreePath); } catch (e) { console.warn('[repo-intel] bootstrap sync failed:', e && e.message); }
  // Independent env-link pass too, so env is present even if the sync above bailed.
  ensureEnvLinks(worktreePath);
}

module.exports = { ensureRepoIntel, getRepoIntelBlock, syncIntelIntoWorktree, ensureWorktreeBootstrap, ensureEnvLinks, ensureReviewTools, upgradeReviewToolsIfDue,
  // Exported for unit testing of the prompt-minimization logic (Item 4).
  loadStructuredIntel, ruleMatchesTouchedPaths, filterGraphSummary, assembleBlock };
