// Repo intelligence: conventions + import-graph context for agent prompts.
//
// On session create we analyze the BASE repo:
//   1. `conventions discover --format json` (steph-dove/conventions) →
//      .conventions/conventions.raw.json with the import graph (fan-in/out,
//      cycles, clusters, endpoint chains). Pure static analysis.
//   2. `klausify init --repo <base> -b <default>` (steph-dove/klausify) →
//      CLAUDE.md, .claude/rules/, conventions-aware skills
//      (.claude/skills/<repo>-review etc.), settings. Includes the Claude
//      CLI enrichment pass (no --skip-enrich) per product decision — the
//      richer CLAUDE.md is worth the API call. klausify skips existing
//      files by default (no --force), so handcrafted CLAUDE.md survives.
//      Fallback when klausify isn't installed: `conventions discover
//      --format claude` guarded by an atomic O_EXCL claim of CLAUDE.md
//      (that CLI overwrites unconditionally).
//
// From the artifacts we build one condensed "repository intelligence" prompt
// block, cached in memory + userData, injected into every agent prompt the
// app composes (PR review, plan, debug, implement). The artifacts themselves
// are also synced into each session worktree (CLAUDE.md, rules, skills) so
// interactive agents pick them up natively — worktrees only contain
// committed files, so without the sync Claude reports "no CLAUDE.md".
//
// Regeneration triggers: artifacts older than a week, artifacts changed on
// disk (mtime), or a new klausify CLI version (stamped into both cache
// layers). Generation is fire-and-forget, per-repo single-flight, and
// broadcast to all windows (started / generated / fresh / failed) so the
// user always sees that analysis is happening. Failures degrade to prompts
// without the block.

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { execFileSync } = require('child_process');
const { app } = require('electron');
const { execFileP } = require('../util/exec');
const { baseRepoForWorktree } = require('../util/git-repo');
const { loadConfig } = require('../util/config');

const inflight = new Map();  // base repo path -> Promise
const memCache = new Map();  // base repo path -> { block, srcMtime, cliVersion }
const baseCache = new Map(); // worktree/repo path -> base repo path (immutable)
const freshNotified = new Set(); // repos already announced as cached this run
const failedAt = new Map();  // base repo path -> last failure timestamp
const FAIL_BACKOFF_MS = 10 * 60 * 1000; // don't re-attempt (or re-toast) failures more often than this

const STALE_MS = 7 * 24 * 60 * 60 * 1000; // weekly refresh
const CLAUDE_MD_CAP = 6000;  // chars of CLAUDE.md included in the block
const RULES_CAP = 4000;      // total chars of rule files included
const CLAUDE_MD_PLACEHOLDER = '# CLAUDE.md\n\n(being generated by conventions-cli — if you can read this, a generation run was interrupted; delete this file)\n';

function artifactPaths(repoPath) {
  return {
    claudeMd: path.join(repoPath, 'CLAUDE.md'),
    rawJson: path.join(repoPath, '.conventions', 'conventions.raw.json'),
    rulesDir: path.join(repoPath, '.claude', 'rules'),
    skillsDir: path.join(repoPath, '.claude', 'skills'),
  };
}

// Hash-named cache file: path-derived names collide (/a/b-c vs /a/b/c) and
// contain Windows-invalid characters.
function cacheFileFor(repoPath) {
  const hash = crypto.createHash('sha1').update(repoPath).digest('hex');
  return path.join(app.getPath('userData'), 'repo-intel', hash + '.md');
}

function mtimeOf(p) {
  try { return fs.statSync(p).mtimeMs; } catch { return 0; }
}

// Newest mtime across all artifacts — the cache-coherency token. Includes the
// rules dir (its mtime bumps when rule files are added/removed).
function artifactsMtime(repoPath) {
  const a = artifactPaths(repoPath);
  return Math.max(mtimeOf(a.claudeMd), mtimeOf(a.rawJson), mtimeOf(a.rulesDir));
}

// klausify CLI version — the regeneration stamp ("redo when there is a new
// version"). Success is memoized for the app run; a null result (not
// installed / transient spawn failure / probe raced the PATH fix) is only
// cached briefly so an install mid-run is picked up.
const KLAUSIFY_VERSION_NULL_TTL_MS = 60 * 1000;
let klausifyVersion = { value: null, at: 0, promise: null };
function getKlausifyVersion() {
  if (klausifyVersion.promise) return klausifyVersion.promise;
  if (klausifyVersion.value) return Promise.resolve(klausifyVersion.value);
  if (Date.now() - klausifyVersion.at < KLAUSIFY_VERSION_NULL_TTL_MS) return Promise.resolve(null);
  const p = execFileP('klausify', ['--version'], { timeout: 15000 })
    .then((r) => String(r.stdout).trim() || null)
    .catch(() => null)
    .then((v) => {
      klausifyVersion = { value: v, at: Date.now(), promise: null };
      return v;
    });
  klausifyVersion.promise = p;
  return p;
}

// Tell every window what's happening so the renderer can toast it — silent
// success reads as "nothing ran" and silent failure hides a missing CLI.
// Lazy require avoids a load-order dependency on state/windows.
function notifyWindows(payload) {
  try {
    const { allWindows } = require('./windows');
    for (const w of allWindows) {
      if (w && !w.isDestroyed()) w.webContents.send('repo-intel-event', payload);
    }
  } catch { /* no windows yet (early boot) — nothing to tell */ }
}

// First-run install of the analysis CLIs (conventions-cli + klausify, both
// on PyPI). Without these, repo intelligence silently never works. Prefer
// pipx (isolated, installs to ~/.local/bin which is already on the spawn
// PATH); fall back to `python3 -m pip install --user`. Single-flight, one
// attempt per app run — never throws. Resolves true when both tools are
// available afterward.
let toolsPromise = null;
// Command name (what we run / detect) vs PyPI package name (what we install)
// — they differ for conventions. Presence is checked with `--help`: the
// `conventions` CLI has no `--version` flag, but both support `--help` and
// exit 0.
const TOOLS = [
  { cmd: 'conventions', pkg: 'conventions-cli' },
  { cmd: 'klausify', pkg: 'klausify' },
];

async function toolPresent(cmd) {
  try {
    await execFileP(cmd, ['--help'], { timeout: 15000 });
    return true;
  } catch {
    return false;
  }
}

async function pickInstaller() {
  try {
    await execFileP('pipx', ['--version'], { timeout: 10000 });
    return { kind: 'pipx' };
  } catch { /* no pipx */ }
  for (const py of ['python3', 'python']) {
    try {
      await execFileP(py, ['-m', 'pip', '--version'], { timeout: 10000 });
      return { kind: 'pip', py };
    } catch { /* try next */ }
  }
  return null;
}

function ensureReviewTools() {
  if (toolsPromise) return toolsPromise;
  toolsPromise = (async () => {
    const missing = [];
    for (const t of TOOLS) if (!(await toolPresent(t.cmd))) missing.push(t);
    if (!missing.length) return true;
    const pkgs = missing.map((t) => t.pkg);
    const manual = 'pipx install ' + pkgs.join(' ');

    const installer = await pickInstaller();
    if (!installer) {
      console.warn('[repo-intel] cannot auto-install', pkgs.join(', '), '— no pipx or pip found');
      notifyWindows({ type: 'tools-failed', missing: pkgs, reason: 'no pipx or pip available', manual });
      return false;
    }

    notifyWindows({ type: 'tools-installing', missing: pkgs, installer: installer.kind });
    console.log('[repo-intel] installing', pkgs.join(', '), 'via', installer.kind);
    try {
      if (installer.kind === 'pipx') {
        // Separate installs so one failure doesn't abort the other.
        for (const pkg of pkgs) {
          await execFileP('pipx', ['install', pkg], { timeout: 5 * 60 * 1000, maxBuffer: 16 * 1024 * 1024 });
        }
      } else {
        await execFileP(installer.py, ['-m', 'pip', 'install', '--user', ...pkgs], {
          timeout: 5 * 60 * 1000, maxBuffer: 16 * 1024 * 1024,
        });
      }
    } catch (err) {
      const first = ((err && err.stderr ? String(err.stderr) : '') || (err && err.message) || '').trim().split('\n').pop();
      console.warn('[repo-intel] tool install failed:', first);
      notifyWindows({ type: 'tools-failed', missing: pkgs, reason: first, manual });
      return false;
    }

    // New binaries land in ~/.local/bin (pipx) or the pip user bin — make
    // them findable in this session without a restart.
    try { require('../bootstrap/app-events').refreshSpawnPath(); } catch {}
    // Drop the cached "missing" klausify version so the next ensure re-probes.
    klausifyVersion = { value: null, at: 0, promise: null };

    const ok = (await Promise.all(missing.map((t) => toolPresent(t.cmd)))).every(Boolean);
    if (ok) {
      console.log('[repo-intel] installed', pkgs.join(', '));
      notifyWindows({ type: 'tools-installed', installed: pkgs });
    } else {
      notifyWindows({ type: 'tools-failed', missing: pkgs, reason: 'installed but not on PATH',
        manual: 'restart Klaussy, or run: ' + manual });
    }
    return ok;
  })();
  return toolsPromise;
}

// Resolve a worktree (or repo) path to its primary checkout — intel belongs
// to the base repo and is shared by every worktree/session under it.
// Memoized: the mapping is immutable for a given path, and the underlying
// `git rev-parse` is a blocking subprocess we don't want on every prompt
// build / IPC call.
function baseFor(repoOrWorktreePath) {
  if (!repoOrWorktreePath) return null;
  if (baseCache.has(repoOrWorktreePath)) return baseCache.get(repoOrWorktreePath);
  const base = baseRepoForWorktree(repoOrWorktreePath) || repoOrWorktreePath;
  baseCache.set(repoOrWorktreePath, base);
  return base;
}

// klausify init prompts interactively for the base branch unless -b is
// passed — resolve it the same way create-task does.
function defaultBranchOf(repoPath) {
  try {
    return execFileSync('git', ['symbolic-ref', 'refs/remotes/origin/HEAD', '--short'], {
      cwd: repoPath, stdio: 'pipe',
    }).toString().trim().replace(/^origin\//, '');
  } catch { /* no origin/HEAD — probe the usual names */ }
  for (const c of ['main', 'master', 'dev', 'develop']) {
    try {
      execFileSync('git', ['rev-parse', '--verify', c], { cwd: repoPath, stdio: 'pipe' });
      return c;
    } catch { /* try next */ }
  }
  return 'main';
}

// Copy the base repo's intel artifacts into a worktree that lacks them.
// Worktrees only materialize COMMITTED files; until the user commits
// CLAUDE.md & co., interactive agents in the worktree would see nothing
// ("no CLAUDE.md provided"). Copies only what's missing, so committed
// versions and per-worktree settings.local.json are never touched.
function syncIntelIntoWorktree(worktreePath) {
  try {
    const base = baseFor(worktreePath);
    if (!base || base === worktreePath) return;
    const entries = [
      ['CLAUDE.md'],
      ['.claude', 'rules'],
      ['.claude', 'skills'],
      // hooks MUST travel with settings.json: klausify's settings register
      // PreToolUse hooks by relative path (.claude/hooks/*.py); a worktree
      // with the settings but not the scripts blocks EVERY Read/Bash call
      // (missing hook exits 2 = deny).
      ['.claude', 'hooks'],
      ['.claude', 'settings.json'],
    ];
    for (const segs of entries) {
      const src = path.join(base, ...segs);
      const dst = path.join(worktreePath, ...segs);
      if (!fs.existsSync(src)) continue;
      if (segs[0] === 'CLAUDE.md') {
        try {
          if (fs.readFileSync(src, 'utf-8') === CLAUDE_MD_PLACEHOLDER) continue;
        } catch { continue; }
        // A previous sync may have raced an unfinished generation and seeded
        // the placeholder — repair it; otherwise never overwrite.
        if (fs.existsSync(dst)) {
          try {
            if (fs.readFileSync(dst, 'utf-8') !== CLAUDE_MD_PLACEHOLDER) continue;
          } catch { continue; }
        }
      } else if (fs.existsSync(dst)) {
        continue;
      }
      fs.mkdirSync(path.dirname(dst), { recursive: true });
      fs.cpSync(src, dst, { recursive: true });
    }
  } catch (e) {
    console.warn('[repo-intel] worktree sync failed for', worktreePath, e.message);
  }
}

// After (re)generation, push the artifacts into every live worktree of this
// base repo — sessions are usually created BEFORE the analysis finishes.
function syncIntelIntoActiveWorktrees(base) {
  try {
    const { instances } = require('./instances');
    for (const [, inst] of instances) {
      if (inst && inst.worktreePath && baseFor(inst.worktreePath) === base) {
        syncIntelIntoWorktree(inst.worktreePath);
      }
    }
  } catch (e) {
    console.warn('[repo-intel] active-worktree sync failed:', e.message);
  }
}

// Condense the raw.json graph rules into a few prompt lines. Defensive
// per-entry: a malformed graph field degrades to "no graph section", never
// to "no block".
function graphSummary(rawJsonPath) {
  let data;
  try {
    data = JSON.parse(fs.readFileSync(rawJsonPath, 'utf-8'));
  } catch {
    return null;
  }
  const lines = [];
  const fanList = (list) => list
    .map((e) => (Array.isArray(e) && e.length >= 2 ? `${e[0]} (${e[1]})` : null))
    .filter(Boolean)
    .join(', ');
  try {
    for (const r of (Array.isArray(data.rules) ? data.rules : [])) {
      if (!r || typeof r.id !== 'string') continue;
      if (/\.import_graph$/.test(r.id)) {
        if (r.description) lines.push('- ' + r.description);
        const s = r.stats || {};
        if (Array.isArray(s.top_fan_in) && s.top_fan_in.length) {
          const t = fanList(s.top_fan_in);
          if (t) lines.push('- Most-depended-on files (fan-in — changes here have wide blast radius): ' + t);
        }
        if (Array.isArray(s.top_fan_out) && s.top_fan_out.length) {
          const t = fanList(s.top_fan_out);
          if (t) lines.push('- Widest-reaching files (fan-out): ' + t);
        }
        if (s.cycle_count) {
          lines.push(`- WARNING: ${s.cycle_count} circular dependency chain(s) exist — do not introduce new edges into them.`);
        }
      } else if (/endpoint_chains|service_dependencies|\.data_flow\./.test(r.id) && r.description) {
        lines.push('- ' + r.description);
      }
    }
  } catch (e) {
    console.warn('[repo-intel] graph summary failed:', e.message);
    if (!lines.length) return null;
  }
  if (!lines.length) return null;
  return '### Code graph (import/dependency analysis)\n\n' + lines.join('\n')
    + '\n\nWhen reviewing or planning changes to a high fan-in file, consider its dependents — regressions there ripple widest.';
}

// Build (or rebuild) the prompt block from on-disk artifacts and refresh both
// cache layers. Synchronous — a handful of small file reads. Caches the
// empty result too (srcMtime-stamped) so repos without artifacts don't pay
// the filesystem walk on every prompt build, while still rebuilding the
// moment artifacts appear.
function buildBlock(basePath, cliVersion) {
  try {
    const a = artifactPaths(basePath);
    const srcMtime = artifactsMtime(basePath);
    const parts = [];

    if (fs.existsSync(a.claudeMd)) {
      let md = fs.readFileSync(a.claudeMd, 'utf-8').trim();
      if (md && md !== CLAUDE_MD_PLACEHOLDER.trim()) {
        if (md.length > CLAUDE_MD_CAP) md = md.slice(0, CLAUDE_MD_CAP) + '\n…(truncated — full file at CLAUDE.md)';
        parts.push('### Repository conventions (CLAUDE.md)\n\n' + md);
      }
    }

    if (fs.existsSync(a.rulesDir)) {
      const chunks = [];
      let budget = RULES_CAP;
      for (const f of fs.readdirSync(a.rulesDir).filter((x) => x.endsWith('.md')).sort()) {
        let t;
        try { t = fs.readFileSync(path.join(a.rulesDir, f), 'utf-8').trim(); } catch { continue; }
        if (t.length > budget) {
          chunks.push(`- Additional path-scoped rules in .claude/rules/${f} (read it when touching matching paths)`);
          continue;
        }
        budget -= t.length;
        chunks.push(`#### .claude/rules/${f}\n\n${t}`);
      }
      if (chunks.length) parts.push('### Path-scoped rules\n\n' + chunks.join('\n\n'));
    }

    const graph = graphSummary(a.rawJson);
    if (graph) parts.push(graph);

    const block = parts.length
      ? '## Repository intelligence\n\n'
        + 'Auto-generated from this repository (klausify / conventions-cli). Treat these conventions, rules, and graph facts as ground truth for this codebase; flag violations of them explicitly.\n\n'
        + parts.join('\n\n')
      : '';

    // Version-stamp semantics: undefined = preserve the existing stamp
    // (rebuilds from getRepoIntelBlock); explicit string — INCLUDING '' —
    // sets it. '' marks "no completed run" so interim/failed builds can't
    // masquerade as finished generations (a falsy-fallback here used to
    // resurrect stale stamps and break both the retry and the
    // uninstall-detection paths).
    const ver = cliVersion !== undefined
      ? cliVersion
      : ((memCache.get(basePath) || {}).cliVersion || '');
    memCache.set(basePath, { block, srcMtime, cliVersion: ver });
    try {
      const f = cacheFileFor(basePath);
      if (block) {
        fs.mkdirSync(path.dirname(f), { recursive: true });
        fs.writeFileSync(f, '<!-- src-mtime:' + srcMtime + ' cli:' + ver + ' -->\n' + block);
      } else {
        // Artifacts gone → the disk cache must go too, or it resurrects
        // deleted intel on the next cold read.
        fs.rmSync(f, { force: true });
      }
    } catch { /* disk cache is best-effort; memory cache is enough */ }
    return block;
  } catch (e) {
    console.warn('[repo-intel] block build failed for', basePath, e.message);
    return '';
  }
}

function readDiskCache(basePath) {
  try {
    const f = cacheFileFor(basePath);
    if (!fs.existsSync(f)) return null;
    const raw = fs.readFileSync(f, 'utf-8');
    // `cli:` is optional: pre-klausify cache files lack it. Their block still
    // loads; the '' stamp means the repo upgrades (one regen with klausify)
    // on next touch — intended for the migration.
    const m = raw.match(/^<!-- src-mtime:([\d.]+)(?: cli:([^>]*))? -->\n/);
    if (!m) return null;
    return { block: raw.slice(m[0].length), srcMtime: Number(m[1]), cliVersion: (m[2] || '').trim() };
  } catch {
    return null;
  }
}

// Unlink raw.json when it doesn't parse — a CLI run killed by the timeout
// can leave a truncated file whose fresh mtime would otherwise vouch for it
// for a week.
function validateRawJson(basePath) {
  const p = artifactPaths(basePath).rawJson;
  if (!fs.existsSync(p)) return;
  try {
    JSON.parse(fs.readFileSync(p, 'utf-8'));
  } catch {
    console.warn('[repo-intel] removing corrupt conventions.raw.json in', basePath);
    try { fs.rmSync(p, { force: true }); } catch {}
  }
}

// Fire-and-forget: make sure the base repo has fresh analysis artifacts,
// regenerating when missing, stale, or built by an older klausify version.
// Single-flight per repo. Never throws.
function ensureRepoIntel(repoOrWorktreePath) {
  let base;
  try {
    base = baseFor(repoOrWorktreePath);
    if (!base || !fs.existsSync(path.join(base, '.git'))) return Promise.resolve();
  } catch {
    return Promise.resolve();
  }
  if (inflight.has(base)) return inflight.get(base);
  // A repo that just failed (CLI missing, scan error) must not restart the
  // whole pipeline — with its started/failed toast pair — on every prompt
  // build. Back off, then retry naturally.
  const lastFail = failedAt.get(base);
  if (lastFail && Date.now() - lastFail < FAIL_BACKOFF_MS) return Promise.resolve();

  const p = (async () => {
    try {
      // First-run: make sure the analysis CLIs exist (auto-installs from
      // PyPI if not). Cheap when already present. If install fails the
      // generation below degrades to whatever artifacts exist.
      // `firstToolsCall` = were WE the caller that actually ran (and toasted)
      // the install? ensureReviewTools is single-flight, so only the first
      // caller's await emits the tools-failed toast; later repos get the
      // cached result silently. The gate below uses this to decide whether a
      // per-repo "unavailable" toast is needed or would just duplicate.
      const firstToolsCall = !toolsPromise;
      const toolsOk = await ensureReviewTools();
      const currentVersion = (await getKlausifyVersion()) || '';
      const a = artifactPaths(base);
      const srcMtime = artifactsMtime(base);
      const cached = memCache.get(base) || readDiskCache(base);
      const stampedVersion = cached ? (cached.cliVersion || '') : null;

      const haveArtifacts = fs.existsSync(a.rawJson);
      const freshEnough = haveArtifacts && (Date.now() - srcMtime < STALE_MS);
      const sameVersion = stampedVersion !== null && stampedVersion === currentVersion;

      if (freshEnough && sameVersion) {
        // Nothing to regenerate — but keep caches coherent, sync worktrees,
        // and STILL tell the user (silent cache hits read as "nothing ran").
        if (!memCache.has(base) || memCache.get(base).srcMtime < srcMtime) {
          buildBlock(base, currentVersion);
        }
        syncIntelIntoActiveWorktrees(base);
        // Announce the cache hit once per repo per app run — evidence
        // without a toast on every single session create.
        if (!freshNotified.has(base)) {
          freshNotified.add(base);
          notifyWindows({ type: 'fresh', repoPath: base });
        }
        return;
      }

      // About to (re)generate — pass 1 unconditionally spawns the `conventions`
      // CLI (the klausify spawn below is separately guarded by currentVersion,
      // so it can't ENOENT). If conventions isn't reachable (install failed, or
      // installed somewhere not on the GUI's PATH), spawning it throws
      // `spawn conventions ENOENT`. Probe first and degrade to whatever
      // artifacts exist instead of crashing into ENOENT.
      const haveConventions = toolsOk || (await toolPresent('conventions'));
      if (!haveConventions) {
        console.warn('[repo-intel] conventions CLI unavailable — skipping generation for', base);
        buildBlock(base, ''); // use a committed CLAUDE.md/graph if present
        syncIntelIntoActiveWorktrees(base);
        failedAt.set(base, Date.now()); // back off; retry naturally later
        // Per-repo signal so a 2nd+ repo in a session still gets feedback: the
        // global tools-failed toast fires only once per app run. Suppress it
        // only for the repo whose own ensureReviewTools call just emitted
        // tools-failed, to avoid a duplicate toast on that same failure.
        if (!firstToolsCall) {
          notifyWindows({ type: 'failed', repoPath: base, error: 'analysis tools not reachable on PATH (ENOENT)' });
        }
        return;
      }

      // "enriching" only when klausify is present AND the user opted into the
      // billed Claude rewrite — drives the toast's "may take a few minutes".
      notifyWindows({ type: 'started', repoPath: base, enriching: !!currentVersion && loadConfig().repoIntelEnrich === true });

      // Pass 1 — graph data: always safe (writes only .conventions/).
      await execFileP('conventions', ['discover', '--format', 'json', '-q'], {
        cwd: base,
        timeout: 5 * 60 * 1000,
        maxBuffer: 16 * 1024 * 1024,
      });
      validateRawJson(base);

      // Make the fast parts available immediately: the import graph (and any
      // existing CLAUDE.md/rules) reach prompts within seconds, instead of
      // waiting minutes for the Claude enrichment on large repos. The
      // enriched block replaces this one when pass 2 finishes. Explicit ''
      // stamp = "no completed run" — only a fully successful pass 2 stamps
      // the version, so failures retry instead of looking done.
      buildBlock(base, '');
      syncIntelIntoActiveWorktrees(base);

      let wroteSkills = false;
      let enrichFailed = false;
      if (currentVersion) {
        // Pass 2a — klausify init: CLAUDE.md + rules + conventions-aware
        // skills + settings. No --force, so existing files (handcrafted
        // CLAUDE.md, customized skills) are preserved. -b is mandatory to
        // keep it non-interactive.
        //
        // Enrichment (the Claude pass that rewrites CLAUDE.md into richer
        // prose) invokes the claude CLI = real API spend on the user's
        // machine. Off by default; --skip-enrich still produces the full
        // skills/rules/settings + a templated CLAUDE.md, just without the
        // LLM rewrite.
        const enrich = loadConfig().repoIntelEnrich === true;
        const initArgs = ['init', '--repo', base, '-b', defaultBranchOf(base)];
        if (!enrich) initArgs.push('--skip-enrich');
        //
        // Guard: klausify's exists-check → write window isn't atomic (it
        // even runs a pip upgrade in between). Snapshot a pre-existing
        // CLAUDE.md and restore it if the run somehow replaced it.
        let preClaudeMd = null;
        try { preClaudeMd = fs.readFileSync(a.claudeMd, 'utf-8'); } catch { /* absent */ }
        const { stdout: initOut } = await execFileP('klausify', initArgs, {
          timeout: 15 * 60 * 1000, // enrichment invokes the claude CLI
          maxBuffer: 16 * 1024 * 1024,
        });
        if (preClaudeMd !== null) {
          try {
            if (fs.readFileSync(a.claudeMd, 'utf-8') !== preClaudeMd) {
              console.warn('[repo-intel] klausify replaced a pre-existing CLAUDE.md — restoring it');
              fs.writeFileSync(a.claudeMd, preClaudeMd);
            }
          } catch { /* deleted mid-run — leave whatever exists */ }
        }
        // conventions-cli swallows enrichment failures (claude missing /
        // unauthenticated / timeout) into a stdout warning and exits 0 —
        // detect it so we don't stamp the run as complete and toast success
        // over an unenriched CLAUDE.md.
        enrichFailed = /could not enrich/i.test(String(initOut || ''));
        wroteSkills = true;
      } else {
        // Pass 2b — fallback without klausify: conventions claude format.
        // That CLI overwrites CLAUDE.md unconditionally, so only run it
        // after atomically claiming the path (`wx` fails if the file exists
        // or appears between checks — e.g. the user ran /init in the
        // freshly spawned session).
        let claimed = false;
        try {
          fs.writeFileSync(a.claudeMd, CLAUDE_MD_PLACEHOLDER, { flag: 'wx' });
          claimed = true;
        } catch { /* CLAUDE.md exists — never let the CLI touch it */ }
        if (claimed) {
          try {
            await execFileP('conventions', ['discover', '--format', 'claude', '-q'], {
              cwd: base,
              timeout: 5 * 60 * 1000,
              maxBuffer: 16 * 1024 * 1024,
            });
          } finally {
            try {
              if (fs.readFileSync(a.claudeMd, 'utf-8') === CLAUDE_MD_PLACEHOLDER) {
                fs.rmSync(a.claudeMd, { force: true });
              }
            } catch {}
          }
        }
      }

      // Stamp the version only on a fully completed run — an enrichment
      // failure leaves the '' stamp so the next session retries.
      buildBlock(base, enrichFailed ? '' : currentVersion);
      syncIntelIntoActiveWorktrees(base);
      failedAt.delete(base);
      console.log('[repo-intel] generated for', base,
        wroteSkills ? (enrichFailed ? '(klausify init, enrichment FAILED)' : '(klausify init + graph)') : '(conventions fallback)');
      notifyWindows({ type: 'generated', repoPath: base, wroteSkills, enrichFailed });
    } catch (err) {
      const first = ((err && err.stderr ? String(err.stderr) : '') || (err && err.message) || '').trim().split('\n')[0];
      console.warn('[repo-intel] generation failed for', base + ':', first);
      failedAt.set(base, Date.now());
      notifyWindows({ type: 'failed', repoPath: base, error: first });
      validateRawJson(base);
      // Still build from whatever artifacts exist (e.g. a committed
      // CLAUDE.md) — '' stamp so the backoff, not the cache, owns the retry.
      buildBlock(base, '');
      syncIntelIntoActiveWorktrees(base);
    } finally {
      inflight.delete(base);
    }
  })();
  inflight.set(base, p);
  return p;
}

// Slim variant for Claude agents running inside a synced worktree: the
// claude CLI loads CLAUDE.md + .claude/rules from the worktree natively (and
// caches that prefix across turns), so re-injecting them into every prompt
// would pay their tokens twice. The import graph is the only section
// CLAUDE.md doesn't carry.
function slimFromBlock(block) {
  if (!block) return '';
  const idx = block.indexOf('### Code graph');
  if (idx === -1) return ''; // nothing CLAUDE.md doesn't already provide
  return '## Repository intelligence\n\n'
    + 'This worktree carries the repo conventions natively (CLAUDE.md + .claude/rules, loaded automatically — treat them as ground truth and flag violations).\n\n'
    + block.slice(idx);
}

// The cached prompt block for a repo/worktree ('' when nothing is available
// yet — prompt builders append it conditionally). Coherent with on-disk
// artifacts: any cache built from older artifacts is rebuilt here.
//
// `agentMode`: pass the agent the prompt targets. For 'claude' with a
// CLAUDE.md present at the queried path (i.e. a synced worktree), the slim
// graph-only block is returned — token saving, see slimFromBlock. Other
// agents (codex/gemini/copilot don't read CLAUDE.md) and unsynced paths get
// the full block.
function getRepoIntelBlock(repoOrWorktreePath, agentMode) {
  let base;
  try {
    base = baseFor(repoOrWorktreePath);
  } catch {
    return '';
  }
  if (!base) return '';
  const srcMtime = artifactsMtime(base);

  let full;
  const hit = memCache.get(base);
  if (hit && hit.srcMtime >= srcMtime) {
    full = hit.block;
  } else {
    const disk = readDiskCache(base);
    if (disk && disk.srcMtime >= srcMtime) {
      memCache.set(base, disk);
      full = disk.block;
    } else {
      full = buildBlock(base);
    }
  }
  if (!full) return '';

  if (agentMode === 'claude') {
    try {
      if (fs.existsSync(path.join(repoOrWorktreePath, 'CLAUDE.md'))) {
        return slimFromBlock(full);
      }
    } catch { /* fall through to full */ }
  }
  return full;
}

module.exports = { ensureRepoIntel, getRepoIntelBlock, syncIntelIntoWorktree, ensureReviewTools };
