// Repo intelligence: conventions + import-graph context for agent prompts.
//
// On session create we run `conventions discover` (steph-dove/conventions —
// pure static analysis, never invokes the claude CLI) against the BASE repo,
// producing .conventions/conventions.raw.json (which carries the import
// graph: fan-in/out, cycles, clusters, endpoint chains) and — only when the
// repo has none — CLAUDE.md and .claude/rules/*.md. From those artifacts we
// build one condensed "repository intelligence" prompt block, cached in
// memory + userData, and inject it into every agent prompt the app composes
// (PR review, plan, debug, implement).
//
// Safety properties:
// - conventions-cli overwrites CLAUDE.md unconditionally, so the CLI only
//   ever runs the claude format after we ATOMICALLY claim the path with a
//   placeholder ({ flag: 'wx' }) — if anything else (a user running /init in
//   the brand-new session, another process) creates CLAUDE.md first, the
//   claim fails and we skip that format entirely. The JSON pass is always
//   safe (writes only under .conventions/).
// - Aborted/corrupt runs can't poison the cache: raw.json is parse-validated
//   after every run (unlinked when invalid) and a placeholder CLAUDE.md left
//   by a failed claude pass is removed.
// - Caches (memory + disk) carry the source artifacts' max mtime and rebuild
//   whenever the artifacts are newer — manual `conventions discover` reruns
//   and CLAUDE.md edits show up without an app restart. Deleting the
//   artifacts deletes the caches too.
// - Generation is fire-and-forget and per-repo single-flight; failures (CLI
//   not installed, scan errors) degrade to prompts without the block.

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { app } = require('electron');
const { execFileP } = require('../util/exec');
const { baseRepoForWorktree } = require('../util/git-repo');

const inflight = new Map();  // base repo path -> Promise
const memCache = new Map();  // base repo path -> { block, srcMtime }
const baseCache = new Map(); // worktree/repo path -> base repo path (immutable)

const STALE_MS = 7 * 24 * 60 * 60 * 1000; // weekly refresh is plenty
const CLAUDE_MD_CAP = 6000;  // chars of CLAUDE.md included in the block
const RULES_CAP = 4000;      // total chars of rule files included
const CLAUDE_MD_PLACEHOLDER = '# CLAUDE.md\n\n(being generated by conventions-cli — if you can read this, a generation run was interrupted; delete this file)\n';

function artifactPaths(repoPath) {
  return {
    claudeMd: path.join(repoPath, 'CLAUDE.md'),
    rawJson: path.join(repoPath, '.conventions', 'conventions.raw.json'),
    rulesDir: path.join(repoPath, '.claude', 'rules'),
  };
}

// Hash-named cache file: path-derived names collide (/a/b-c vs /a/b/c) and
// contain Windows-invalid characters.
function cacheFileFor(repoPath) {
  const hash = crypto.createHash('sha1').update(repoPath).digest('hex');
  return path.join(app.getPath('userData'), 'repo-intel', hash + '.md');
}

function mtimeOf(p) {
  try { return fs.statSync(p).mtimeMs; } catch { return 0; }
}

// Newest mtime across all artifacts — the cache-coherency token. Includes the
// rules dir (its mtime bumps when rule files are added/removed).
function artifactsMtime(repoPath) {
  const a = artifactPaths(repoPath);
  return Math.max(mtimeOf(a.claudeMd), mtimeOf(a.rawJson), mtimeOf(a.rulesDir));
}

// Resolve a worktree (or repo) path to its primary checkout — intel belongs
// to the base repo and is shared by every worktree/session under it.
// Memoized: the mapping is immutable for a given path, and the underlying
// `git rev-parse` is a blocking subprocess we don't want on every prompt
// build / IPC call.
function baseFor(repoOrWorktreePath) {
  if (!repoOrWorktreePath) return null;
  if (baseCache.has(repoOrWorktreePath)) return baseCache.get(repoOrWorktreePath);
  const base = baseRepoForWorktree(repoOrWorktreePath) || repoOrWorktreePath;
  baseCache.set(repoOrWorktreePath, base);
  return base;
}

// Condense the raw.json graph rules into a few prompt lines. The interesting
// rules are <lang>.data_flow.import_graph (stats: top_fan_in/out, cycles,
// clusters) plus endpoint-chain / service-dependency descriptions. Defensive
// per-entry: a malformed graph field degrades to "no graph section", never to
// "no block" (a throw here used to discard CLAUDE.md and rules too).
function graphSummary(rawJsonPath) {
  let data;
  try {
    data = JSON.parse(fs.readFileSync(rawJsonPath, 'utf-8'));
  } catch {
    return null;
  }
  const lines = [];
  const fanList = (list) => list
    .map((e) => (Array.isArray(e) && e.length >= 2 ? `${e[0]} (${e[1]})` : null))
    .filter(Boolean)
    .join(', ');
  try {
    for (const r of (Array.isArray(data.rules) ? data.rules : [])) {
      if (!r || typeof r.id !== 'string') continue;
      if (/\.import_graph$/.test(r.id)) {
        if (r.description) lines.push('- ' + r.description);
        const s = r.stats || {};
        if (Array.isArray(s.top_fan_in) && s.top_fan_in.length) {
          const t = fanList(s.top_fan_in);
          if (t) lines.push('- Most-depended-on files (fan-in — changes here have wide blast radius): ' + t);
        }
        if (Array.isArray(s.top_fan_out) && s.top_fan_out.length) {
          const t = fanList(s.top_fan_out);
          if (t) lines.push('- Widest-reaching files (fan-out): ' + t);
        }
        if (s.cycle_count) {
          lines.push(`- WARNING: ${s.cycle_count} circular dependency chain(s) exist — do not introduce new edges into them.`);
        }
      } else if (/endpoint_chains|service_dependencies|\.data_flow\./.test(r.id) && r.description) {
        lines.push('- ' + r.description);
      }
    }
  } catch (e) {
    console.warn('[repo-intel] graph summary failed:', e.message);
    if (!lines.length) return null;
  }
  if (!lines.length) return null;
  return '### Code graph (import/dependency analysis)\n\n' + lines.join('\n')
    + '\n\nWhen reviewing or planning changes to a high fan-in file, consider its dependents — regressions there ripple widest.';
}

// Build (or rebuild) the prompt block from on-disk artifacts and refresh both
// cache layers. Synchronous — a handful of small file reads. Caches the
// empty result too (srcMtime-stamped) so repos without artifacts don't pay
// the filesystem walk on every prompt build, while still rebuilding the
// moment artifacts appear (their mtime exceeds the cached stamp).
function buildBlock(basePath) {
  try {
    const a = artifactPaths(basePath);
    const srcMtime = artifactsMtime(basePath);
    const parts = [];

    if (fs.existsSync(a.claudeMd)) {
      let md = fs.readFileSync(a.claudeMd, 'utf-8').trim();
      if (md && md !== CLAUDE_MD_PLACEHOLDER.trim()) {
        if (md.length > CLAUDE_MD_CAP) md = md.slice(0, CLAUDE_MD_CAP) + '\n…(truncated — full file at CLAUDE.md)';
        parts.push('### Repository conventions (CLAUDE.md)\n\n' + md);
      }
    }

    if (fs.existsSync(a.rulesDir)) {
      const chunks = [];
      let budget = RULES_CAP;
      for (const f of fs.readdirSync(a.rulesDir).filter((x) => x.endsWith('.md')).sort()) {
        let t;
        try { t = fs.readFileSync(path.join(a.rulesDir, f), 'utf-8').trim(); } catch { continue; }
        if (t.length > budget) {
          chunks.push(`- Additional path-scoped rules in .claude/rules/${f} (read it when touching matching paths)`);
          continue;
        }
        budget -= t.length;
        chunks.push(`#### .claude/rules/${f}\n\n${t}`);
      }
      if (chunks.length) parts.push('### Path-scoped rules\n\n' + chunks.join('\n\n'));
    }

    const graph = graphSummary(a.rawJson);
    if (graph) parts.push(graph);

    const block = parts.length
      ? '## Repository intelligence\n\n'
        + 'Auto-generated from this repository (conventions-cli). Treat these conventions, rules, and graph facts as ground truth for this codebase; flag violations of them explicitly.\n\n'
        + parts.join('\n\n')
      : '';

    memCache.set(basePath, { block, srcMtime });
    try {
      const f = cacheFileFor(basePath);
      if (block) {
        fs.mkdirSync(path.dirname(f), { recursive: true });
        fs.writeFileSync(f, '<!-- src-mtime:' + srcMtime + ' -->\n' + block);
      } else {
        // Artifacts gone → the disk cache must go too, or it resurrects
        // deleted intel on the next cold read.
        fs.rmSync(f, { force: true });
      }
    } catch { /* disk cache is best-effort; memory cache is enough */ }
    return block;
  } catch (e) {
    console.warn('[repo-intel] block build failed for', basePath, e.message);
    return '';
  }
}

// Unlink raw.json when it doesn't parse — a CLI run killed by the timeout
// can leave a truncated file whose fresh mtime would otherwise vouch for it
// for a week.
function validateRawJson(basePath) {
  const p = artifactPaths(basePath).rawJson;
  if (!fs.existsSync(p)) return;
  try {
    JSON.parse(fs.readFileSync(p, 'utf-8'));
  } catch {
    console.warn('[repo-intel] removing corrupt conventions.raw.json in', basePath);
    try { fs.rmSync(p, { force: true }); } catch {}
  }
}

// Fire-and-forget: make sure the base repo has fresh conventions artifacts,
// regenerating with the conventions CLI when missing/stale. Single-flight
// per repo. Never throws.
function ensureRepoIntel(repoOrWorktreePath) {
  let base;
  try {
    base = baseFor(repoOrWorktreePath);
    if (!base || !fs.existsSync(path.join(base, '.git'))) return Promise.resolve();
  } catch {
    return Promise.resolve();
  }
  if (inflight.has(base)) return inflight.get(base);

  const a = artifactPaths(base);
  const srcMtime = artifactsMtime(base);
  if (fs.existsSync(a.rawJson) && Date.now() - srcMtime < STALE_MS) {
    // Fresh enough — rebuild the block only if the artifacts are newer than
    // what either cache layer was built from.
    const cached = memCache.get(base);
    if (!cached || cached.srcMtime < srcMtime) buildBlock(base);
    return Promise.resolve();
  }

  const p = (async () => {
    try {
      // Pass 1 — always safe: writes only .conventions/ (json format).
      await execFileP('conventions', ['discover', '--format', 'json', '-q'], {
        cwd: base,
        timeout: 5 * 60 * 1000,
        maxBuffer: 16 * 1024 * 1024,
      });
      validateRawJson(base);

      // Pass 2 — claude format (CLAUDE.md + .claude/rules). The CLI
      // overwrites CLAUDE.md unconditionally, so we only run it after
      // atomically claiming the path: `wx` fails if the file exists or
      // appears between our earlier checks and now (e.g. the user ran /init
      // in the freshly spawned session).
      let claimed = false;
      try {
        fs.writeFileSync(a.claudeMd, CLAUDE_MD_PLACEHOLDER, { flag: 'wx' });
        claimed = true;
      } catch { /* CLAUDE.md exists — never let the CLI touch it */ }
      if (claimed) {
        try {
          await execFileP('conventions', ['discover', '--format', 'claude', '-q'], {
            cwd: base,
            timeout: 5 * 60 * 1000,
            maxBuffer: 16 * 1024 * 1024,
          });
        } finally {
          // A failed/aborted claude pass must not leave our placeholder
          // masquerading as a real CLAUDE.md.
          try {
            if (fs.readFileSync(a.claudeMd, 'utf-8') === CLAUDE_MD_PLACEHOLDER) {
              fs.rmSync(a.claudeMd, { force: true });
            }
          } catch {}
        }
      }

      buildBlock(base);
      console.log('[repo-intel] generated for', base, claimed ? '(with CLAUDE.md)' : '(graph only — CLAUDE.md already present)');
    } catch (err) {
      const first = ((err && err.stderr ? String(err.stderr) : '') || (err && err.message) || '').trim().split('\n')[0];
      console.warn('[repo-intel] generation failed for', base + ':', first);
      validateRawJson(base);
      // Still build from whatever artifacts exist (e.g. a committed CLAUDE.md).
      buildBlock(base);
    } finally {
      inflight.delete(base);
    }
  })();
  inflight.set(base, p);
  return p;
}

// The cached prompt block for a repo/worktree ('' when nothing is available
// yet — prompt builders append it conditionally). Coherent with on-disk
// artifacts: any cache built from older artifacts is rebuilt here.
function getRepoIntelBlock(repoOrWorktreePath) {
  let base;
  try {
    base = baseFor(repoOrWorktreePath);
  } catch {
    return '';
  }
  if (!base) return '';
  const srcMtime = artifactsMtime(base);

  const hit = memCache.get(base);
  if (hit && hit.srcMtime >= srcMtime) return hit.block;

  try {
    const f = cacheFileFor(base);
    if (fs.existsSync(f)) {
      const raw = fs.readFileSync(f, 'utf-8');
      const m = raw.match(/^<!-- src-mtime:([\d.]+) -->\n/);
      if (m && Number(m[1]) >= srcMtime) {
        const block = raw.slice(m[0].length);
        memCache.set(base, { block, srcMtime: Number(m[1]) });
        return block;
      }
    }
  } catch { /* fall through to building from artifacts */ }
  return buildBlock(base);
}

module.exports = { ensureRepoIntel, getRepoIntelBlock };
